apiVersion: v1
kind: Pod
metadata:
  name: worker1
  namespace: default
spec:
  containers:
  - image: fernandofreire/cep-worker:cloud
    name: worker1
    imagePullPolicy: Always
    env:
    - name: WORKER_ID
      value: "1"
    - name: LBA                                      
      value: "inputsimilarity"
    resources:
      requests:
        memory: "10000Mi"
      limits:
        memory: "10100Mi" #43000
  restartPolicy: OnFailure
  serviceAccountName: cep-worker-sa
  automountServiceAccountToken: true

