apiVersion: v1
kind: Pod
metadata:
  name: worker1
  namespace: default
spec:
  containers:
  - image: fernandofreire/cep-worker:cloud
    name: worker1
    imagePullPolicy: Always
    env:
    - name: WORKER_ID
      value: "1"
    - name: LBA                                      
      value: "inputsimilarity" # or "stateusage"
    resources:
      requests:
        memory: "4000Mi"
        cpu: "400m"
      limits:
        memory: "4100Mi" #4300Mi
        cpu: "400m"
  restartPolicy: OnFailure
  serviceAccountName: cep-worker-sa
  automountServiceAccountToken: true

