version: '3.7'

services:
  redis-cep:
    container_name: redis-cep
    image: fernandofreire/redis-cep:mini
    volumes:
      - 'redis-cep'
    ports:
      - 6379:6379
  cep-worker:
    container_name: cep-worker
    image: fernandofreire/cep-worker:cloud
#    command: java -cp target/CEPWorker-1.0.jar worker.Processor
    environment:
    - MODE=nomono
    - INITIATE_OTHER_WORKERS=false
    - RABBITMQ_HOST=rabbitmq-cep
    - REDIS_CEP_HOST=redis-cep
    - LOGS_THREADHANDLER=true
    - LOGS_INCLUSION=false
    - LOGS_EVENTHANDLER=false
    - LOGS_RESOURCEANALYSIS=false
    - LBA=inputsimilarity
    - TIMEOUT_A=30000
    depends_on:
      - redis-cep
  rabbitmq-cep:
    container_name: rabbitmq-cep
    image: fernandofreire/rabbitmq-cep:latest
    ports:
      - 5672:5672
  experiment:
    container_name: experiment
    image: fernandofreire/experiment:no-t-no-d
    environment:
    - TYPES=savethis
    - REDIS_HOST=redis-cep
    - CHECK_REDIS=true
    - RABBITMQ_HOST=rabbitmq-cep
    depends_on:
      - redis-cep
    volumes:
      - saved:/experiment/data
    


networks:
  default:
    external:
      name: platform 

volumes:
  saved:
